service: thundra-knex-mysql2

custom:
  thundraApiKey: #TODO: enter your API key here
  stage: dev #Configure your stage if you want
  region: us-west-2 #Configure your AWS region if you want
  profile: default #Configure your AWS profile if you want
  thundra:
    node:
      layer:
        version: latest


provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  profile: ${self:custom.profile}
  memorySize: 256
  timeout: 300
  environment:
      thundra_apiKey: ${self:custom.thundraApiKey}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:*
      Resource: [
        "*"
      ]

plugins:
  - serverless-plugin-thundra

functions:
  thundra-knex-mysql2:
    name: thundra-knex-mysql2
    handler: index.handler