service: sampling-demo

custom:
  thundraApiKey: #TODO: enter your API key here
  stage: dev #Configure your stage if you want
  region: us-west-2 #Configure your AWS region if you want
  profile: default #Configure your AWS profile if you want

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  profile: ${self:custom.profile}
  memorySize: 256
  timeout: 300
  environment:
      thundra_apiKey: ${self:custom.thundraApiKey}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:*
      Resource: [
        "*"
      ]

functions:
  sampling-demo-all:
    name: sampling-demo-all
    handler: index.handler
  sampling-demo-composite:
    name: sampling-demo-composite
    handler: index.handler_composite
  sampling-demo-custom:
    name: sampling-demo-custom
    handler: index.handler_custom
