service: apollo-server-lambda-example

custom:
  deploymentBucket: #TODO: enter your AWS S3 deployment bucket here
  thundraApiKey: #TODO: enter your API key here
  stage: dev #Configure your stage if you want
  region: us-west-2 #Configure your AWS region if you want
  profile: default #Configure your AWS profile if you want
  thundra:
    node:
      layer:
        version: latest

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  profile: ${self:custom.profile}
  deploymentBucket: ${self:custom.deploymentBucket}
  memorySize: 256
  timeout: 30
  environment:
      thundra_apiKey: ${self:custom.thundraApiKey}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:*
      Resource: [
        "*"
      ]

plugins:
  - serverless-plugin-thundra

functions:
  apollo-server-lambda-example:
    name: apollo-server-lambda-example
    handler: index.handler
    events:
      - http:
          path: graphql
          method: any