service: automatic-instrumentation-example

custom:
  deploymentBucket: #TODO: enter your AWS S3 deployment bucket here
  thundraApiKey: #TODO: enter your API key here
  stage: dev #Configure your stage if you want
  region: #Configure your AWS region if you want
  profile: default #Configure your AWS profile if you want
  thundra:
    node:
      layer:
        version: latest


provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  profile: ${self:custom.profile}
  deploymentBucket: ${self:custom.deploymentBucket}
  memorySize: 256
  timeout: 300
  environment:
      thundra_apiKey: ${self:custom.thundraApiKey}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:*
        - dynamodb:*
      Resource: [
        "*"
      ]

plugins:
  - serverless-plugin-thundra

functions:
  automatic-instrumentation-example:
    name: automatic-instrumentation-example
    handler: index.handler